name: daily-scrape

on:
  schedule:
    # 03:00 UTC = 06:00 Cairo
    - cron: "0 3 * * *"
  workflow_dispatch: {} # lets you trigger manually

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scheduled scraper
        run: |
          python main.py
